# Generated by Django 3.0.1 on 2020-01-01 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_launchpad_establishment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launch',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='launchpad',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='launchpad',
            name='no_employees',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='launchpad',
            name='use_period',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='launchpad',
            name='used_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='launchvehicle',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='launchvehicle',
            name='max_distance',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='orbitalgrouping',
            name='accuracy',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='orbitalgrouping',
            name='coverage',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='orbitalgrouping',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orbitalgrouping',
            name='first_launch_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orbitalgrouping',
            name='no_planes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orbitalgrouping',
            name='no_spacecrafts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orbitalgrouping',
            name='no_spacecrafts_on_plane',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orbitalgrouping',
            name='orbit_height',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='orbitalgrouping',
            name='orbital_inclination',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='orbitalgrouping',
            name='orbital_period',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='spacecraft',
            name='accuracy',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='spacecraft',
            name='coverage_diameter',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='spacecraft',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spacecraft',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='spacecraft',
            name='orbital_inclination',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='spacecraft',
            name='orbital_period',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='spacetug',
            name='autonomous_flight_time',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='spacetug',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spacetug',
            name='first_launch_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spacetug',
            name='no_flights',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
