# Generated by Django 3.0.1 on 2020-01-02 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200101_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spacetug',
            name='no_inclusions',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
