# Generated by Django 3.0.2 on 2020-01-04 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200103_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parserlaunch',
            name='parse_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
