# Generated by Django 3.0.2 on 2020-01-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200104_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launchvehicle',
            name='space_tugs',
            field=models.ManyToManyField(null=True, to='core.SpaceTug'),
        ),
    ]
