# Generated by Django 3.0.2 on 2020-01-05 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200105_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launchvehicle',
            name='space_tugs',
            field=models.ManyToManyField(blank=True, null=True, to='core.SpaceTug'),
        ),
    ]
