# Generated by Django 3.0.2 on 2020-01-05 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200105_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launchvehicle',
            name='space_tugs',
            field=models.ManyToManyField(blank=True, to='core.SpaceTug'),
        ),
    ]
