# Generated by Django 3.0.2 on 2020-01-05 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200105_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launch',
            name='result',
            field=models.CharField(choices=[('EMERGENCY', 'Аварийный'), ('SUCCESS', 'Успешный'), ('FAILED', 'Неуспешный'), ('UPCOMING', 'Предстоящий')], max_length=12),
        ),
    ]
