# Generated by Django 3.0.2 on 2020-01-06 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200105_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spaceobservatory',
            name='flight_duration',
        ),
    ]
