# Generated by Django 3.0.2 on 2020-01-06 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_spaceobservatory_flight_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spacestation',
            name='days_in_orbit',
        ),
        migrations.AddField(
            model_name='spacestation',
            name='in_orbit_since',
            field=models.DateField(default='2010-01-01'),
            preserve_default=False,
        ),
    ]
