# Generated by Django 3.0.2 on 2020-01-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200106_0226'),
    ]

    operations = [
        migrations.AddField(
            model_name='launchpad',
            name='image',
            field=models.ImageField(max_length=255, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='launchvehicle',
            name='image',
            field=models.ImageField(max_length=255, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='orbitalgrouping',
            name='image',
            field=models.ImageField(max_length=255, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='spacecraft',
            name='image',
            field=models.ImageField(max_length=255, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='spaceobservatory',
            name='image',
            field=models.ImageField(max_length=255, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='spacestation',
            name='image',
            field=models.ImageField(max_length=255, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='spacetug',
            name='image',
            field=models.ImageField(max_length=255, null=True, upload_to='images/'),
        ),
    ]
