# Generated by Django 3.0.2 on 2020-01-06 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20200106_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spacecraft',
            name='power',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
