# Generated by Django 3.0.2 on 2020-01-06 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20200106_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spacestation',
            name='launch_date',
        ),
    ]
