# Generated by Django 3.0.2 on 2020-01-06 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_spacestation_launch_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spacestation',
            name='docked_spacecrafts',
            field=models.ManyToManyField(blank=True, to='core.Spacecraft'),
        ),
    ]
