# Generated by Django 3.0.2 on 2020-01-07 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20200106_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='launchvehicle',
            name='no_launches',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spaceobservatory',
            name='launch_time',
            field=models.TimeField(default='12:30:57'),
            preserve_default=False,
        ),
    ]
